name: deploy
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Docker build
        env:
          JDBC_URL: ${{secrets.JDBC_URL}}
          USERNAME: ${{secrets.USERNAME}}
          PASSWORD: ${{secrets.PASSWORD}}
        run: |
          docker build -t mahesh21319/mahesh-m . --build-arg JDBC_URL=$JDBC_URL --build-arg USERNAME=$USERNAME --build-arg PASSWORD=$PASSWORD
          docker push mahesh21319/mahesh-m
      - name: Docker pull and RUN
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.INSTANCE_HOST}}
          username: ec2-user
          key: ${{secrets.PRIVATE_KEY}}
          envs: GITHUB_SHA
          script: |
            docker login -u ${{secrets.DOCKER_USER}} --password-stdin ${{secrets.DOCKER_PASSWORD}}
            docker pull mahesh21319/mahesh-m
            docker stop backend_server
            docker rm backend_server
            docker run -detach --name backend_server -p 80:8080 -e JDBC_URL='${{secrets.JDBC_URL}}' -e USERNAME='${{secrets.USERNAME}}' -e PASSWORD='${{secrets.PASSWORD}}' mahesh21319/mahesh-m:latest
